- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Asterisk
  - Pebble
  - Shoukou
  - Meta
  - Box
  - Lambda
  - Bagel
  # WD EDIT START - white dream maps
  - DryDock
  - Moose
  - WhiteBox
  # WD EDIT END
