- type: department
  id: Logistics # DeltaV - Logistics Department replacing Cargo
  name: department-Logistics
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  - MailCarrier # Nyanotrasen - MailCarrier, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Cargo/mail-carrier.yml
  weight: -4 # WWDP
  buttonStyle: ButtonColorCargoDepartment # WWDP

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -3 # WWDP
  roles:
  - Bartender
  - Botanist
  - Boxer
  # - Chaplain # DeltaV - Move Chaplain into Epistemics
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  # - Lawyer # DeltaV - Move Lawyer into Justice
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker
  - MartialArtist # Nyanotrasen - MartialArtist, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/martialartist.yml
  # - Prisoner # WWDP moved to Security
  - Gladiator # Nyanotrasen - Gladiator, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/gladiator.yml
  - Hobo # White Dream
  buttonStyle: ButtonColorCivilianDepartment # WWDP

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Captain
  - CentralCommandOfficial
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - Maid # White Dream
  - ChiefJustice # DeltaV - chief justice is in command staff
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  - AdministrativeAssistant # Delta V - Administrative Assistant, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Command/admin_assistant.yml
  primary: false
  weight: -1 # WWDP
  buttonStyle: ButtonColorCommandDepartment # WWDP

# - type: department # WWDP disabled
#   id: Dignitary
#   name: department-Dignitary
#   description: department-Dignitary-description
#   color: "#33FE6D"
#   roles:
#   - BlueshieldOfficer # Goobstation
#   - NanotrasenRepresentative # Goobstation
#   - Magistrate # Goobstation
#   primary: false
#   weight: 101

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - SeniorEngineer
  - StationEngineer
  - TechnicalAssistant
  weight: -5 # WWDP
  buttonStyle: ButtonColorEngineeringDepartment # WWDP

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - SeniorPhysician
  - MedicalBorg  # Delta V - Medical Borg, see Resources/Prototypes/DeltaV/Roles/Jobs/Medical/medicalborg.yml
  weight: -6 # WWDP
  buttonStyle: ButtonColorMedicalDepartment # WWDP

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: -2 # WWDP
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - SeniorOfficer
  - Detective
  - Warden
  - PrisonGuard # Nyanotrasen - PrisonGuard, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Security/prisonguard.yml
  - Brigmedic # DeltaV - Brigmedic, see Resources/Prototypes/DeltaV/Roles/Jobs/Security/brigmedic.yml
  - Prisoner # Nyanotrasen - Prisoner, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/prisoner.yml # WWDP moved to SEC
  buttonStyle: ButtonColorSecurityDepartment # WWDP

- type: department
  id: Epistemics # DeltaV - Epistemics Department replacing Science
  name: department-Epistemics
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - SeniorResearcher
  - Scientist
  - ResearchAssistant
  - Chaplain # DeltaV - Move Chaplain into Epistemics
  - ForensicMantis # Nyanotrasen - ForensicMantis, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Epistemics/forensicmantis.yml
  - Librarian
  - Roboticist
  weight: -7 # WWDP
  buttonStyle: ButtonColorScienceDepartment # WWDP

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi
  weight: -8 # WWDP
  buttonStyle: ButtonColorSiliconDepartment # WWDP

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: -42 # WWDP
#   roles: # WWDP disabled
#   - Boxer
#   - Reporter
#   - Zookeeper
#   - Psychologist
#   - MartialArtist # Nyanotrasen - MartialArtist, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/martialartist.yml
#   - Gladiator # Nyanotrasen - Gladiator, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/gladiator.yml
#   - Prisoner # Nyanotrasen - Prisoner, see Resrouces/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/prisoner.yml
#   - Brigmedic # DeltaV - Corpsman, see Resources/Prototypes/DeltaV/Roles/Jobs/Security/brigmedic.yml
#   primary: false
  buttonStyle: ButtonColorSpecificDepartment # WWDP
