- type: entity
  parent: SimpleSpaceMobBase
  id: BaseMobXenomorph
  name: alien
  suffix: ""
  abstract: true
  components:
  - type: Xenomorph
    weedHeal:
      groups:
        Burn: -5
        Toxin: -5
        Airloss: -10
        Brute: -5
  - type: PlasmaVessel
  - type: ShowInfectedIcons
  - type: ThermalVision
    toggleAction: ToggleThermalVisionAlien
    color: "#7d0cc9"
    lightRadius: 10
  - type: NameIdentifier
    group: GenericNumber
  - type: CombatMode
    combatToggleAction: ActionCombatModeToggleAlien
    canDisarm: true
  - type: MovementSpeedModifier
    baseWalkSpeed: 3
    baseSprintSpeed: 4.5
  - type: NpcFactionMember
    factions:
    - Xeno
  - type: Deathgasp
    prototype: XenomorphDeathgasp
  - type: DamageStateVisuals
    rotate: true
    states:
      Alive:
        Base: aliens
      Critical:
        Base: aliens_unconscious
      Dead:
        Base: aliens_dead
  - type: MobThresholds
    thresholds:
      0: Alive
      125: Critical
      135: Dead
    stateAlertDict:
      Alive: AlienHealth
      Critical: AlienCrit
      Dead: AlienDead
  - type: SlowOnDamage
    speedModifierThresholds:
      70: 0.9
      85: 0.7
      100: 0.6
  - type: Damageable
    damageContainer: Biological
    damageModifierSet: Xenomorph
  - type: Stamina
    critThreshold: 500
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.25
        density: 1000
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: Tag
    tags:
    - DoorBumpOpener
    - FootstepSound
  - type: Bloodstream
    bloodReagent: FluorosulfuricAcid
    bloodMaxVolume: 250
    bloodlossDamage:
      types:
        Bloodloss: 0.05
    bloodlossHealDamage:
      types:
        Bloodloss: -1
  - type: MeleeWeapon
    altDisarm: true
    angle: 0
    soundHit:
      collection: AlienClaw
    animation: WeaponArcBite
    damage:
      groups:
        Brute: 20
  - type: TypingIndicator
    proto: alien
  - type: Temperature
    heatDamageThreshold: 360
    coldDamageThreshold: -150
    currentTemperature: 310.15
  - type: ZombieImmune
  - type: StatusEffects
    allowed:
    - Stun
    - KnockedDown
  - type: NoSlip
  - type: Perishable
    molsPerSecondPerUnitMass: 0.0005
  - type: LizardAccent
  - type: Speech
    speechSounds: Xenomorph
    speechVerb: SmallMob
  - type: Vocal
    sounds:
      Male: Xenomorph
      Female: Xenomorph
      Unsexed: Xenomorph
  - type: LanguageKnowledge
    speaks:
    - Xeno
    - XenoHivemind
    understands:
    - Xeno
    - XenoHivemind
    - Hissing
    - Draconic
  - type: SSDIndicator
  - type: Inventory
    templateId: alien
  - type: Emoting
  - type: BodyEmotes
    soundsId: GeneralBodyEmotes
  - type: GuideHelp
    guides:
    - Xenomorphs

- type: entity
  parent: BaseMobXenomorph
  id: BaseMobXenomorphAdult
  abstract: true
  components:
  - type: VomitAction
    thirstAdded: 5.0
    hungerAdded: 5.0
  - type: Devourer
    devourTime: 3
    consumes:
    - Alive
    - Critical
  - type: Tool
    speedModifier: 1.5
    qualities:
    - Prying
  - type: Prying
    pryPowered: true
  - type: Hands
  - type: ComplexInteraction
  - type: Puller
    needsHands: false
  - type: IdExaminable
  - type: InventorySlots
  - type: Stripping
  - type: Strippable
  - type: SurgeryTarget
  - type: UserInterface
    interfaces:
      enum.StrippingUiKey.Key:
        type: StrippableBoundUserInterface
      enum.InstrumentUiKey.Key:
        type: InstrumentBoundUserInterface
        requireInputValidation: false
      enum.SurgeryUIKey.Key:
        type: SurgeryBui
  - type: RotationVisuals
    defaultRotation: 90
    horizontalRotation: 90
  - type: Body
    prototype: XenomorphLarge
  - type: Dna

# BASE FACEHUGGER

- type: entity
  parent:
  - BaseItem
  - BaseMob
  - MobDamageable
  - MobFlammable
  id: BaseFacehugger
  abstract: true
  components:
  - type: Sprite
    drawdepth: SmallMobs
    sprite: _White/Mobs/Aliens/Xenomorphs/facehugger.rsi
    layers:
    - map: [ "enum.DamageStateVisualLayers.Base" ]
      state: facehugger
  - type: Xenomorph
    greetingText: alien-facehugger-greeting
    weedHeal:
      groups:
        Burn: -0.5
        Toxin: -0.5
        Airloss: -0.10
        Brute: -0.5
  - type: ReproducingXenomorph
  - type: Item
    sprite: _White/Mobs/Aliens/Xenomorphs/facehugger_inhands.rsi
    size: Small
  - type: Buckle
  - type: Damageable
    damageContainer: Biological
    damageModifierSet: Xenomorph
  - type: MobState
  - type: MobThresholds
    thresholds:
      0: Alive
      25: Dead
    stateAlertDict:
      Alive: AlienHealth
      Dead: AlienDead
  - type: DamageStateVisuals
    states:
      Alive:
        Base: facehugger
      Dead:
        Base: facehugger_impregnated
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.2
        density: 100
        mask:
        - SmallMobMask
        layer:
        - BulletImpassable
  - type: Tag
    tags:
    - AlienItem
    - WhitelistChameleon
    - MonkeyWearable
    - PetWearable
    - Facehugger
  - type: StaticPrice
    price: 1000
  - type: Clothing
    sprite: _White/Clothing/Mask/facehugger.rsi
    slots:
    - Mask
  - type: BreathMask
  - type: Blindfold
  - type: GuideHelp
    guides:
    - XenomorphFacehugger
